### PR TITLE
fix invalid json

### PR DESCRIPTION
**Pull request by asbyth**

### CODE REVIEW

**Comment by RDIL** [comment]
@CoalCoding

**Comment by OPAmqericaHPE** [comment]
Waa

**Comment by RDIL** [comment]
@OPAmqericaHPE JSON stands for JavaScript Object Notation. JSON is a lightweight format for storing and transporting data. JSON is often used when data is sent from a server to a web page. JSON is "self-describing" and easy to understand.  In this case, the JSON was broken so @asbyth fixed it.

**Comment by OPAmqericaHPE** [comment]
Ooh. Ok. Noted :)

**Pull request merged**
